# Agree on 2 prime numbers for generator and prime modulas
print("Please agree on 2 prime numbers that will be publicly shared to generate a key!")

print("Please enter a prime number for the generator:", end="")
primeGen = int(input())

print("Please enter a prime number for the modulator:", end="")
primeMod = int(input())
print()

#Get user ones private number
print("Please enter user one's private key:", end="")
userOnePrivateKey = int(input())

#generate a publicly shared number to send to user two
userOneShared = primeGen**userOnePrivateKey%primeMod
print("user one's shard key is", userOneShared)
print()

#Get user two's private number
print("Please enter user twos's private key:", end="")
userTwoPrivateKey = int(input())

#generate a publicly shared number to send to user one
userTwoShared = primeGen**userTwoPrivateKey%primeMod

print("user two's shard key is", userTwoShared)
print()

# Once both users have shared the public keys we can generate a key using the results
# the key is generated by using the other uses shared key to the power of the first
# current uses private key mod the prime mod we agreed on at the start
userOneFinalKey = userTwoShared**userOnePrivateKey%primeMod
print("userOneFinalKey:", userOneFinalKey, "=", userTwoShared, "**", userOnePrivateKey, "%", primeMod)
print()

userTwoFinalKey = userOneShared**userTwoPrivateKey%primeMod
print("userTwoFinalKey:", userTwoFinalKey, "=", userOneShared, "**", userTwoPrivateKey, "%", primeMod)
print()

if userOneFinalKey == userTwoFinalKey:
    print("Both users have the key:", userOneFinalKey)
else:
    print("user one has the key:", userOneFinalKey, "and user two has the key", userTwoFinalKey)